### ISSUE TITLE
Implement: Package Overview

### ISSUE THREAD

**Issue by RomainMuller** [cdklabs/construct-hub-webapp#6]
Implement basic package overview, which is a page with the following information:

- README of the package.
- Language specific API reference.
- Package metadata (name, description, license, version...)

## Epic

- [x] https://github.com/cdklabs/construct-hub-webapp/issues/42
- [ ] https://github.com/cdklabs/construct-hub-webapp/issues/43
- [ ] https://github.com/cdklabs/construct-hub-webapp/issues/44
- [ ] https://github.com/cdklabs/construct-hub-webapp/issues/45
- [ ] https://github.com/cdklabs/construct-hub-webapp/issues/46
- [ ] https://github.com/cdklabs/construct-hub-webapp/issues/47
